--
-- File generated with SQLiteStudio v3.1.0 on Wed Jan 12 17:10:42 2022
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: cfg_system
CREATE TABLE cfg_system (id INTEGER PRIMARY KEY, param CHAR (32), value CHAR (32));
INSERT INTO cfg_system (id, param, value) VALUES (1, 'sessionid', 'ho7vk67sqrjua8sme0pqhsjgdq');
INSERT INTO cfg_system (id, param, value) VALUES (2, 'timezone', 'America/Detroit');
INSERT INTO cfg_system (id, param, value) VALUES (3, 'i2sdevice', 'None');
INSERT INTO cfg_system (id, param, value) VALUES (4, 'hostname', 'moode');
INSERT INTO cfg_system (id, param, value) VALUES (5, 'browsertitle', 'moOde Player');
INSERT INTO cfg_system (id, param, value) VALUES (6, 'airplayname', 'Moode Airplay');
INSERT INTO cfg_system (id, param, value) VALUES (7, 'upnpname', 'Moode UPNP');
INSERT INTO cfg_system (id, param, value) VALUES (8, 'dlnaname', 'Moode DLNA');
INSERT INTO cfg_system (id, param, value) VALUES (9, 'airplaysvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (10, 'upnpsvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (11, 'dlnasvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (12, 'alsa_output_mode', 'plughw');
INSERT INTO cfg_system (id, param, value) VALUES (13, 'rotaryenc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (14, 'autoplay', '0');
INSERT INTO cfg_system (id, param, value) VALUES (15, 'rbsvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (16, 'mpdver', '');
INSERT INTO cfg_system (id, param, value) VALUES (17, 'rbactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (18, 'adevname', 'Pi HDMI 1');
INSERT INTO cfg_system (id, param, value) VALUES (19, 'clkradio_mode', 'Disabled');
INSERT INTO cfg_system (id, param, value) VALUES (20, 'clkradio_item', '0');
INSERT INTO cfg_system (id, param, value) VALUES (21, 'clkradio_name', '');
INSERT INTO cfg_system (id, param, value) VALUES (22, 'clkradio_start', '06,00,AM,0,0,0,0,0,0,0');
INSERT INTO cfg_system (id, param, value) VALUES (23, 'clkradio_stop', '07,00,AM,0,0,0,0,0,0,0');
INSERT INTO cfg_system (id, param, value) VALUES (24, 'clkradio_volume', '10');
INSERT INTO cfg_system (id, param, value) VALUES (25, 'clkradio_action', 'None');
INSERT INTO cfg_system (id, param, value) VALUES (26, 'playhist', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (27, 'phistsong', '');
INSERT INTO cfg_system (id, param, value) VALUES (28, 'library_utf8rep', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (29, 'current_view', 'playback,folder');
INSERT INTO cfg_system (id, param, value) VALUES (30, 'timecountup', '0');
INSERT INTO cfg_system (id, param, value) VALUES (31, 'accent_color', 'Emerald');
INSERT INTO cfg_system (id, param, value) VALUES (32, 'volknob', '0');
INSERT INTO cfg_system (id, param, value) VALUES (33, 'volmute', '0');
INSERT INTO cfg_system (id, param, value) VALUES (34, 'alsavolume_max', '100');
INSERT INTO cfg_system (id, param, value) VALUES (35, 'alsavolume', '0');
INSERT INTO cfg_system (id, param, value) VALUES (36, 'amixname', 'HDMI');
INSERT INTO cfg_system (id, param, value) VALUES (37, 'mpdmixer', 'software');
INSERT INTO cfg_system (id, param, value) VALUES (38, 'extra_tags', 'album,genre,track,disc,date,composer,conductor,performer,encoded');
INSERT INTO cfg_system (id, param, value) VALUES (39, 'rsmafterapl', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (40, 'lcdup', '0');
INSERT INTO cfg_system (id, param, value) VALUES (41, 'library_show_genres', 'Yes');
INSERT INTO cfg_system (id, param, value) VALUES (42, 'extmeta', '0');
INSERT INTO cfg_system (id, param, value) VALUES (43, 'i2soverlay', 'None');
INSERT INTO cfg_system (id, param, value) VALUES (44, 'hdwrrev', '');
INSERT INTO cfg_system (id, param, value) VALUES (45, 'crossfeed', 'Off');
INSERT INTO cfg_system (id, param, value) VALUES (46, 'bluez_pcm_buffer', '500000');
INSERT INTO cfg_system (id, param, value) VALUES (47, 'upnp_browser', '0');
INSERT INTO cfg_system (id, param, value) VALUES (48, 'library_onetouch_album', 'Play');
INSERT INTO cfg_system (id, param, value) VALUES (49, 'radio_pos', '-1');
INSERT INTO cfg_system (id, param, value) VALUES (50, 'aplactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (51, 'ipaddr_timeout', '90');
INSERT INTO cfg_system (id, param, value) VALUES (52, 'ashufflesvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (53, 'ashuffle', '0');
INSERT INTO cfg_system (id, param, value) VALUES (54, 'camilladsp', 'off');
INSERT INTO cfg_system (id, param, value) VALUES (55, 'cdsp_fix_playback', 'Yes');
INSERT INTO cfg_system (id, param, value) VALUES (56, 'camilladsp_quickconv', '0;Sennheiser_HD800S_L_44100Hz_32b.raw;Sennheiser_HD800S_R_44100Hz_32b.raw;S32LE''');
INSERT INTO cfg_system (id, param, value) VALUES (57, 'alsa_loopback', 'Off');
INSERT INTO cfg_system (id, param, value) VALUES (58, 'keyboard', 'us');
INSERT INTO cfg_system (id, param, value) VALUES (59, 'localui', '0');
INSERT INTO cfg_system (id, param, value) VALUES (60, 'toggle_songid', '');
INSERT INTO cfg_system (id, param, value) VALUES (61, 'slsvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (62, 'hdmiport', '1');
INSERT INTO cfg_system (id, param, value) VALUES (63, 'cpugov', 'ondemand');
INSERT INTO cfg_system (id, param, value) VALUES (64, 'pairing_agent', '0');
INSERT INTO cfg_system (id, param, value) VALUES (65, 'pkgid_suffix', '');
INSERT INTO cfg_system (id, param, value) VALUES (66, 'lib_pos', '-1,-1,-1');
INSERT INTO cfg_system (id, param, value) VALUES (67, 'mpdcrossfade', '0');
INSERT INTO cfg_system (id, param, value) VALUES (68, 'eth0chk', '0');
INSERT INTO cfg_system (id, param, value) VALUES (69, 'usb_auto_mounter', 'udisks-glue');
INSERT INTO cfg_system (id, param, value) VALUES (70, 'rsmafterbt', '0');
INSERT INTO cfg_system (id, param, value) VALUES (71, 'rotenc_params', '100 2 3 23 24');
INSERT INTO cfg_system (id, param, value) VALUES (72, 'shellinabox', '0');
INSERT INTO cfg_system (id, param, value) VALUES (73, 'alsaequal', 'Off');
INSERT INTO cfg_system (id, param, value) VALUES (74, 'eqfa12p', 'Off');
INSERT INTO cfg_system (id, param, value) VALUES (75, 'p3wifi', '1');
INSERT INTO cfg_system (id, param, value) VALUES (76, 'p3bt', '1');
INSERT INTO cfg_system (id, param, value) VALUES (77, 'cardnum', '0');
INSERT INTO cfg_system (id, param, value) VALUES (78, 'btsvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (79, 'btname', 'Moode Bluetooth');
INSERT INTO cfg_system (id, param, value) VALUES (80, 'btmulti', '0');
INSERT INTO cfg_system (id, param, value) VALUES (81, 'feat_bitmask', '97207');
INSERT INTO cfg_system (id, param, value) VALUES (82, 'library_recently_added', '2592000000');
INSERT INTO cfg_system (id, param, value) VALUES (83, 'btactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (84, 'touchscn', '1');
INSERT INTO cfg_system (id, param, value) VALUES (85, 'scnblank', '600');
INSERT INTO cfg_system (id, param, value) VALUES (86, 'scnrotate', '0');
INSERT INTO cfg_system (id, param, value) VALUES (87, 'scnbrightness', '255');
INSERT INTO cfg_system (id, param, value) VALUES (88, 'themename', 'Default');
INSERT INTO cfg_system (id, param, value) VALUES (89, 'res_software_upd_url', 'http://d3oddxvgenziko.cloudfront.net');
INSERT INTO cfg_system (id, param, value) VALUES (90, 'alphablend', '1.0');
INSERT INTO cfg_system (id, param, value) VALUES (91, 'adaptive', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (92, 'audioout', 'Local');
INSERT INTO cfg_system (id, param, value) VALUES (93, 'audioin', 'Local');
INSERT INTO cfg_system (id, param, value) VALUES (94, 'slactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (95, 'rsmaftersl', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (96, 'mpdmixer_local', 'software');
INSERT INTO cfg_system (id, param, value) VALUES (97, 'wrkready', '0');
INSERT INTO cfg_system (id, param, value) VALUES (98, 'scnsaver_timeout', 'Never');
INSERT INTO cfg_system (id, param, value) VALUES (99, 'pixel_aspect_ratio', 'Default');
INSERT INTO cfg_system (id, param, value) VALUES (100, 'favorites_name', 'Favorites');
INSERT INTO cfg_system (id, param, value) VALUES (101, 'spotifysvc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (102, 'spotifyname', 'Moode Spotify');
INSERT INTO cfg_system (id, param, value) VALUES (103, 'spotactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (104, 'rsmafterspot', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (105, 'library_covsearchpri', 'Embedded cover');
INSERT INTO cfg_system (id, param, value) VALUES (106, 'library_hiresthm', 'Auto');
INSERT INTO cfg_system (id, param, value) VALUES (107, 'library_pixelratio', '1');
INSERT INTO cfg_system (id, param, value) VALUES (108, 'usb_auto_updatedb', '0');
INSERT INTO cfg_system (id, param, value) VALUES (109, 'cover_backdrop', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (110, 'cover_blur', '20px');
INSERT INTO cfg_system (id, param, value) VALUES (111, 'cover_scale', '1.25');
INSERT INTO cfg_system (id, param, value) VALUES (112, 'rsmafterrb', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (113, 'library_tagview_artist', 'Artist');
INSERT INTO cfg_system (id, param, value) VALUES (114, 'scnsaver_style', 'Gradient (Linear)');
INSERT INTO cfg_system (id, param, value) VALUES (115, 'ashuffle_filter', 'None');
INSERT INTO cfg_system (id, param, value) VALUES (116, 'mpd_httpd', '0');
INSERT INTO cfg_system (id, param, value) VALUES (117, 'mpd_httpd_port', '8000');
INSERT INTO cfg_system (id, param, value) VALUES (118, 'mpd_httpd_encoder', 'lame');
INSERT INTO cfg_system (id, param, value) VALUES (119, 'invert_polarity', '0');
INSERT INTO cfg_system (id, param, value) VALUES (120, 'inpactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (121, 'rsmafterinp', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (122, 'gpio_svc', '0');
INSERT INTO cfg_system (id, param, value) VALUES (123, 'library_ignore_articles', 'a,an,the');
INSERT INTO cfg_system (id, param, value) VALUES (124, 'volknob_mpd', '0');
INSERT INTO cfg_system (id, param, value) VALUES (125, 'volknob_preamp', '0');
INSERT INTO cfg_system (id, param, value) VALUES (126, 'library_albumview_sort', 'Artist');
INSERT INTO cfg_system (id, param, value) VALUES (127, 'kernel_architecture', '32-bit');
INSERT INTO cfg_system (id, param, value) VALUES (128, 'wake_display', '0');
INSERT INTO cfg_system (id, param, value) VALUES (129, 'usb_volknob', '0');
INSERT INTO cfg_system (id, param, value) VALUES (130, 'led_state', '1,1');
INSERT INTO cfg_system (id, param, value) VALUES (131, 'library_tagview_covers', 'Yes');
INSERT INTO cfg_system (id, param, value) VALUES (132, 'library_tagview_sort', 'Artist');
INSERT INTO cfg_system (id, param, value) VALUES (133, 'library_ellipsis_limited_text', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (134, 'preferences_modal_state', '1,0,0,0,0');
INSERT INTO cfg_system (id, param, value) VALUES (135, 'font_size', 'Normal');
INSERT INTO cfg_system (id, param, value) VALUES (136, 'volume_step_limit', '10');
INSERT INTO cfg_system (id, param, value) VALUES (137, 'volume_mpd_max', '100');
INSERT INTO cfg_system (id, param, value) VALUES (138, 'library_thumbnail_columns', '6/2 (Default)');
INSERT INTO cfg_system (id, param, value) VALUES (139, 'library_encoded_at', '9');
INSERT INTO cfg_system (id, param, value) VALUES (140, 'first_use_help', 'y,y');
INSERT INTO cfg_system (id, param, value) VALUES (141, 'playlist_art', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (142, 'ashuffle_mode', 'Track');
INSERT INTO cfg_system (id, param, value) VALUES (143, 'radioview_sort_group', 'Name,No grouping');
INSERT INTO cfg_system (id, param, value) VALUES (144, 'radioview_show_hide', 'No action,No action');
INSERT INTO cfg_system (id, param, value) VALUES (145, 'renderer_backdrop', 'No');
INSERT INTO cfg_system (id, param, value) VALUES (146, 'library_flatlist_filter', 'full_lib');
INSERT INTO cfg_system (id, param, value) VALUES (147, 'library_flatlist_filter_str', '');
INSERT INTO cfg_system (id, param, value) VALUES (148, 'library_misc_options', 'No,Album@Artist (Default)');
INSERT INTO cfg_system (id, param, value) VALUES (149, 'recorder_status', 'Not installed');
INSERT INTO cfg_system (id, param, value) VALUES (150, 'recorder_storage', '/mnt/SDCARD');
INSERT INTO cfg_system (id, param, value) VALUES (151, 'volume_db_display', '0');
INSERT INTO cfg_system (id, param, value) VALUES (152, 'search_site', 'Google');
INSERT INTO cfg_system (id, param, value) VALUES (153, 'cuefiles_ignore', '1');
INSERT INTO cfg_system (id, param, value) VALUES (154, 'recorder_album_tag', 'Recorded YYYY-MM-DD');
INSERT INTO cfg_system (id, param, value) VALUES (155, 'inplace_upd_applied', '0');
INSERT INTO cfg_system (id, param, value) VALUES (156, 'show_npicon', 'Yes');
INSERT INTO cfg_system (id, param, value) VALUES (157, 'show_cvpb', 'Yes');
INSERT INTO cfg_system (id, param, value) VALUES (158, 'multiroom_tx', 'Off');
INSERT INTO cfg_system (id, param, value) VALUES (159, 'multiroom_rx', 'Disabled');
INSERT INTO cfg_system (id, param, value) VALUES (160, 'rxactive', '0');
INSERT INTO cfg_system (id, param, value) VALUES (161, 'library_onetouch_radio', 'Play');
INSERT INTO cfg_system (id, param, value) VALUES (162, 'library_tagview_genre', 'Genres');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
