---
devices:
  adjust_period: 3
  capture:
    type: File
    channels: 2
    filename: /dev/stdin
    format: S32LE
  chunksize: 4096
  enable_rate_adjust: false
  playback:
    type: Alsa
    channels: 2
    device: plughw:2,0
    format: S32LE
  queuelimit: 1
  rate_measure_interval: 1
  samplerate: 44100
  silence_threshold: 0
  silence_timeout: 0
  stop_on_rate_change: false
  target_level: 1024
  volume_ramp_time: 150
mixers:
  XF_IN:
    channels:
      in: 2
      out: 4
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -9.500000
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -1.500000
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 1
        gain: -1.500000
        inverted: false
        mute: false
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: -9.500000
        inverted: false
        mute: false
  XF_OUT:
    channels:
      in: 4
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
      - channel: 3
        gain: 0
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
      - channel: 0
        gain: 0
        inverted: false
        mute: false
filters:
  XF_Cross_Lowpass:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 650
      q: 0.500000
  XF_Direct_Highshelf:
    type: Biquad
    parameters:
      type: HighshelfFO
      freq: 900
      gain: 1.500000
pipeline:
- type: Mixer
  name: XF_IN
- type: Filter
  channel: 0
  names:
  - XF_Cross_Lowpass
- type: Filter
  channel: 1
  names:
  - XF_Direct_Highshelf
- type: Filter
  channel: 2
  names:
  - XF_Direct_Highshelf
- type: Filter
  channel: 3
  names:
  - XF_Cross_Lowpass
- type: Mixer
  name: XF_OUT
...
