devices:
  samplerate: 44100
  chunksize: 1024
  queuelimit: 1
  volume_ramp_time: 150
  capture:
    type: File
    channels: 2
    filename: "/dev/stdin"
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: "plughw:0,0"
    format: S32LE
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: -3
            inverted: false
pipeline:
  - type: Mixer
    name: stereo

