---
devices:
  adjust_period: 10
  capture:
    type: File
    channels: 2
    filename: /dev/stdin
    format: S32LE
  chunksize: 4096
  enable_rate_adjust: false
  playback:
    type: Alsa
    channels: 2
    device: plughw:2,0
    format: S32LE
  queuelimit: 1
  rate_measure_interval: 1
  samplerate: 44100
  silence_threshold: -60
  silence_timeout: 3
  stop_on_rate_change: false
  target_level: 0
  volume_ramp_time: 150
filters:
  Stereo Image:
    parameters:
      gain: -6
      inverted: false
      mute: false
    type: Gain
  pregain:
    parameters:
      gain: -3
      inverted: false
      mute: false
    type: Gain
mixers:
  MS:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
      - channel: 1
        gain: -3
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
      - channel: 1
        gain: -3
        inverted: true
        mute: false
pipeline:
- channel: 0
  names:
  - pregain
  type: Filter
- channel: 1
  names:
  - pregain
  type: Filter
- name: MS
  type: Mixer
- channel: 1
  names:
  - Stereo Image
  type: Filter
- name: MS
  type: Mixer
...
