devices:
  adjust_period: 10
  capture:
    channels: 2
    extra_samples: 0
    filename: /dev/stdin
    format: S16LE
    read_bytes: 0
    skip_bytes: 0
    type: File
  chunksize: 4096
  enable_rate_adjust: false
  playback:
    channels: 3
    device: plughw:0,0
    format: S16LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: 1
  samplerate: 44100
  silence_threshold: -60
  silence_timeout: 3
  stop_on_rate_change: false
  target_level: 0
  volume_ramp_time: 150
filters:
  AP:
    parameters:
      freq: 5000
      q: 0.5
      type: Allpass
    type: Biquad
  HP:
    parameters:
      freq: 5000
      q: 0.5
      type: Highpass
    type: Biquad
  LP:
    parameters:
      freq: 5000
      q: 0.5
      type: Lowpass
    type: Biquad
  pregain:
    parameters:
      gain: -3
      inverted: false
      mute: false
    type: Gain
mixers:
  DIV:
    channels:
      in: 3
      out: 3
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
      - channel: 1
        gain: -3
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: true
        mute: false
      - channel: 1
        gain: -3
        inverted: true
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 2
        gain: -1
        inverted: false
        mute: false
  LCR:
    channels:
      in: 3
      out: 3
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: -3
        inverted: false
        mute: false
      - channel: 2
        gain: -3
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 1
        gain: -3
        inverted: false
        mute: false
      - channel: 2
        gain: -3
        inverted: true
        mute: false
  MS:
    channels:
      in: 2
      out: 3
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
      - channel: 1
        gain: -3
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
      - channel: 1
        gain: -3
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
      - channel: 1
        gain: -3
        inverted: true
        mute: false
pipeline:
- name: MS
  type: Mixer
- channel: 0
  names:
  - HP
  type: Filter
- channel: 1
  names:
  - LP
  type: Filter
- name: DIV
  type: Mixer
- name: LCR
  type: Mixer
