description: Mikhail Naganov, customize with own IR correction.
devices:
  adjust_period: 3
  capture:
    type: Stdin
    channels: 2
    extra_samples: null
    format: S24LE
    read_bytes: null
    skip_bytes: null
  capture_samplerate: 44100
  chunksize: 4096
  enable_rate_adjust: false
  playback:
    type: Alsa
    channels: 2
    device: hw:0,0
    format: S24LE
  queuelimit: 1
  rate_measure_interval: 1
  samplerate: 44100
  silence_threshold: 0
  silence_timeout: 0
  stop_on_rate_change: false
  target_level: 1024
  volume_ramp_time: 150
filters:
  XF_Cross_Highshelf:
    description: null
    parameters:
      freq: 750
      gain: -0.3
      type: HighshelfFO
    type: Biquad
  XF_Cross_Peaking_EQ:
    description: null
    parameters:
      freq: 180
      gain: 0.5
      q: 0.55
      type: Peaking
    type: Biquad
  XF_Direct_Highshelf:
    description: null
    parameters:
      freq: 200
      gain: 2.3
      type: HighshelfFO
    type: Biquad
  ir_hpcf:
    description: null
    parameters:
      channel: 0
      filename: ../coeffs/V3-Sennheiser_HD800S_HpCF_A.wav
      type: Wav
    type: Conv
  ir_l_input_l_ear:
    description: null
    parameters:
      channel: 0
      filename: ../coeffs/V3-BRIR_R02_P1_E0_A-30.wav
      type: Wav
    type: Conv
  ir_l_input_r_ear:
    description: null
    parameters:
      channel: 1
      filename: ../coeffs/V3-BRIR_R02_P1_E0_A-30.wav
      type: Wav
    type: Conv
  ir_r_input_l_ear:
    description: null
    parameters:
      channel: 0
      filename: ../coeffs/V3-BRIR_R02_P1_E0_A+30.wav
      type: Wav
    type: Conv
  ir_r_input_r_ear:
    description: null
    parameters:
      channel: 1
      filename: ../coeffs/V3-BRIR_R02_P1_E0_A+30.wav
      type: Wav
    type: Conv
  mastergain:
    description: null
    parameters:
      gain: -18
      inverted: false
      mute: false
      scale: null
    type: Gain
mixers:
  XF_IN:
    channels:
      in: 2
      out: 4
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -9.9
        inverted: false
        mute: false
        scale: null
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -2.3
        inverted: false
        mute: false
        scale: null
    - dest: 2
      mute: false
      sources:
      - channel: 1
        gain: -2.3
        inverted: false
        mute: false
        scale: null
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: -9.9
        inverted: false
        mute: false
        scale: null
  XF_OUT:
    channels:
      in: 4
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: null
      - channel: 3
        gain: -3
        inverted: false
        mute: false
        scale: null
    - dest: 1
      mute: false
      sources:
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: null
      - channel: 0
        gain: -3
        inverted: false
        mute: false
        scale: null
pipeline:
- bypassed: null
  description: null
  name: XF_IN
  type: Mixer
- bypassed: null
  channels:
  - 0
  description: null
  names:
  - XF_Cross_Highshelf
  - XF_Cross_Peaking_EQ
  - ir_l_input_r_ear
  type: Filter
- bypassed: null
  channels:
  - 1
  description: null
  names:
  - XF_Direct_Highshelf
  type: Filter
- bypassed: null
  channels:
  - 2
  description: null
  names:
  - XF_Direct_Highshelf
  type: Filter
- bypassed: null
  channels:
  - 3
  description: null
  names:
  - XF_Cross_Highshelf
  - XF_Cross_Peaking_EQ
  - ir_r_input_l_ear
  type: Filter
- bypassed: null
  description: null
  name: XF_OUT
  type: Mixer
- bypassed: null
  channels:
  - 0
  description: null
  names:
  - ir_hpcf
  type: Filter
- bypassed: null
  channels:
  - 1
  description: null
  names:
  - ir_hpcf
  type: Filter
processors: null
title: Crossfeed Mikhail
