description: M-S (Mid-Side) matrix with side signal increased.
devices:
  adjust_period: 10
  capture:
    type: Stdin
    channels: 2
    extra_samples: null
    format: S24LE
    read_bytes: null
    skip_bytes: null
  capture_samplerate: null
  chunksize: 4096
  enable_rate_adjust: false
  playback:
    type: Alsa
    channels: 2
    device: hw:0,0
    format: S24LE
  queuelimit: 1
  rate_measure_interval: 1
  samplerate: 44100
  silence_threshold: -60
  silence_timeout: 3
  stop_on_rate_change: false
  target_level: 0
  volume_ramp_time: 150
filters:
  Stereo Image:
    description: null
    parameters:
      gain: 6
      inverted: false
      mute: false
      scale: null
    type: Gain
  pregain:
    description: null
    parameters:
      gain: -3
      inverted: false
      mute: false
      scale: null
    type: Gain
mixers:
  MS:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
        scale: null
      - channel: 1
        gain: -3
        inverted: false
        mute: false
        scale: null
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
        scale: null
      - channel: 1
        gain: -3
        inverted: true
        mute: false
        scale: null
pipeline:
- bypassed: null
  channels:
  - 0
  description: null
  names:
  - pregain
  type: Filter
- bypassed: null
  channels:
  - 1
  description: null
  names:
  - pregain
  type: Filter
- bypassed: null
  description: null
  name: MS
  type: Mixer
- bypassed: null
  channels:
  - 1
  description: null
  names:
  - Stereo Image
  type: Filter
- bypassed: null
  description: null
  name: MS
  type: Mixer
processors: null
title: MS-Matrix Wide
