devices:
  capture:
    channels: 2
    format: S16LE
    type: Stdin
  chunksize: 4096
  playback:
    channels: 2
    device: plughw:0,0
    format: S16LE
    type: Alsa
  queuelimit: 1
  samplerate: 44100
  volume_ramp_time: 150
filters:
  mastergain:
    parameters:
      gain: 0
    type: Gain
pipeline:
- channels:
  - 0
  names:
  - mastergain
  type: Filter
- channels:
  - 1
  names:
  - mastergain
  type: Filter
