devices:
  samplerate: 44100
  chunksize: 4096
  queuelimit: 1
  volume_ramp_time: 150
  capture:
    channels: 2
    format: S16LE
    type: Stdin
  playback:
    type: Alsa
    channels: 2
    device: "plughw:0,0"
    format: S16LE
filters:
    mastergain:
        type: Gain
        parameters:
            gain: __IR_GAIN__
    ir_left:
      type: Conv
      parameters:
        type: __IR_TYPE__
        filename: __IR_LEFT__
        __IR_PARAMS_L__
    ir_right:
      type: Conv
      parameters:
        type: __IR_TYPE__
        filename: __IR_RIGHT__
        __IR_PARAMS_R__
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
pipeline:
  - type: Mixer
    name: stereo
  - type: Filter
    channels:
    - 0
    names:
      - mastergain
      - ir_left
  - type: Filter
    channels:
    - 1
    names:
      - mastergain
      - ir_right

